package syntax.backend.runways.service

import syntax.backend.runways.dto.*
import syntax.backend.runways.entity.Course
import java.util.*

interface CourseApiService {
    fun getCourseData(courseId: UUID): Course
    fun createCourse(requestCourseDTO: RequestCourseDTO, userId: String): UUID
    fun updateCourse(requestUpdateCourseDTO: RequestUpdateCourseDTO, userId: String): UUID
    fun deleteCourse(courseId: UUID, userId: String): String
    fun addBookmark(courseId: UUID, userId: String): String
    fun removeBookmark(courseId: UUID, userId: String): String
    fun increaseHits(courseId: UUID): String
    fun getCourseById(courseId: UUID, userId: String): ResponseCourseDetailDTO
    fun createCourseByLLM(llmRequestDTO: LlmRequestDTO, userId: String): List<AutoGeneratedCourseDTO>
    fun getCombinedRecommendCourses(nx: Double, ny: Double, city: String, userId: String): List<ResponseRecommendCourseDTO>
}
